"""Self-Improvement PR Creator - Auto-PR Generation for Approved Suggestions.

Creates draft PRs for approved suggestions:
- Validates config changes against ScoutConfig schema
- Creates git branches
- Applies config changes or creates tool stubs
- Creates draft PRs with evidence via GitHub CLI
"""

import json
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

# Paths
SCOUT_CONFIG_PATH = Path("~/.scout/config.yaml").expanduser()
REPO_ROOT = Path(__file__).parent.parent.parent.parent


@dataclass
class PRResult:
    """Result of PR creation attempt."""

    success: bool
    branch_name: Optional[str]
    pr_url: Optional[str]
    error: Optional[str]
    changes: list[str]


def run_cmd(
    cmd: list[str], cwd: Optional[Path] = None, check: bool = True
) -> subprocess.CompletedProcess:
    """Run a shell command and return the result."""
    return subprocess.run(
        cmd,
        cwd=cwd or REPO_ROOT,
        capture_output=True,
        text=True,
        check=check,
    )


def check_gh_authenticated() -> bool:
    """Check if GitHub CLI is authenticated."""
    try:
        result = run_cmd(["gh", "auth", "status"], check=False)
        return result.returncode == 0
    except FileNotFoundError:
        return False


def create_branch(branch_name: str) -> bool:
    """Create a new git branch.

    Args:
        branch_name: Name of the branch to create

    Returns:
        True if successful
    """
    # First check if branch already exists
    result = run_cmd(["git", "rev-parse", "--verify", branch_name], check=False)
    if result.returncode == 0:
        # Branch exists, check it out
        run_cmd(["git", "checkout", branch_name])
        return True

    # Create and checkout new branch
    run_cmd(["git", "checkout", "-b", branch_name])
    return True


def apply_config_change(key: str, value: any, dry_run: bool = False) -> tuple[bool, str, list[str]]:
    """Apply a configuration change.

    Args:
        key: Config key in dot notation (e.g., "limits.hourly_budget")
        value: New value for the config
        dry_run: If True, don't actually apply the change

    Returns:
        Tuple of (success, error_message, list_of_changed_files)
    """
    import yaml
    from scout.config import ScoutConfig

    # Ensure config directory exists
    SCOUT_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Load current config
    current = {}
    if SCOUT_CONFIG_PATH.exists():
        with open(SCOUT_CONFIG_PATH) as f:
            current = yaml.safe_load(f) or {}

    # Validate the change against ScoutConfig
    test_config = current.copy()
    parts = key.split(".")

    # Navigate to the nested key
    d = test_config
    for part in parts[:-1]:
        d = d.setdefault(part, {})
    d[parts[-1]] = value

    # Validate with ScoutConfig
    try:
        validated = ScoutConfig.from_dict(test_config)  # noqa: F841
    except Exception as e:
        return False, f"Config validation failed: {e}", []

    if dry_run:
        return True, f"Would set {key} = {value}", [str(SCOUT_CONFIG_PATH)]

    # Create backup
    backup_path = SCOUT_CONFIG_PATH.with_suffix(".yaml.backup")
    shutil.copy2(SCOUT_CONFIG_PATH, backup_path)

    # Apply the change
    with open(SCOUT_CONFIG_PATH, "w") as f:
        yaml.dump(test_config, f, default_flow_style=False)

    return True, f"Set {key} = {value}", [str(SCOUT_CONFIG_PATH), str(backup_path)]


def create_tool_stub(tool_name: str, dry_run: bool = False) -> tuple[bool, str, list[str]]:
    """Create a new tool stub file.

    Args:
        tool_name: Name of the tool to create
        dry_run: If True, don't actually create the file

    Returns:
        Tuple of (success, error_message, list_of_created_files)
    """
    # Look for tools directory - try multiple locations
    possible_dirs = [
        REPO_ROOT / "scout" / "tools",
        REPO_ROOT / "src" / "scout" / "tools",
        REPO_ROOT / "tools",
    ]
    tools_dir = None
    for d in possible_dirs:
        if d.exists():
            tools_dir = d
            break
    
    if tools_dir is None:
        return False, f"Tools directory not found in: {possible_dirs}", []

    tool_path = tools_dir / f"{tool_name}.py"

    if tool_path.exists():
        return False, f"Tool already exists: {tool_path}", []

    if dry_run:
        return True, f"Would create tool at {tool_path}", [str(tool_path)]

    # Create tool stub from template
    template = f'''"""Scout tool: {tool_name}.

Auto-generated by Scout self-improvement system.
"""

from scout.tools.base import Tool, ToolResult


class {tool_name.replace("_", "").title()}Tool(Tool):
    """Tool for {tool_name} operations."""
    
    name = "{tool_name}"
    description = "Auto-generated tool for {tool_name}"
    
    async def execute(self, *args, **kwargs) -> ToolResult:
        """Execute the tool."""
        # TODO: Implement {tool_name} logic
        return ToolResult(
            success=True,
            content="Tool stub for {tool_name} - implement logic here"
        )


# Tool instance for registration
tool = {tool_name.replace("_", "").title()}Tool()
'''

    tool_path.write_text(template)

    return True, f"Created tool stub at {tool_path}", [str(tool_path)]


def add_to_gitignore(paths: list[str], dry_run: bool = False) -> tuple[bool, str, list[str]]:
    """Add paths to .scoutignore or similar ignore file.

    Args:
        paths: List of paths to ignore
        dry_run: If True, don't actually modify the file

    Returns:
        Tuple of (success, error_message, list_of_changed_files)
    """
    ignore_file = REPO_ROOT / ".scoutignore"

    existing_content = ""
    if ignore_file.exists():
        existing_content = ignore_file.read_text()

    new_paths = []
    for path in paths:
        if path not in existing_content:
            new_paths.append(path)

    if not new_paths:
        return True, "All paths already in ignore file", []

    if dry_run:
        return True, f"Would add {new_paths} to {ignore_file}", [str(ignore_file)]

    with open(ignore_file, "a") as f:
        for path in new_paths:
            f.write(f"\n# Added by self-improvement\n{path}\n")

    return True, f"Added {new_paths} to {ignore_file}", [str(ignore_file)]


def create_draft_pr(
    title: str,
    body: str,
    labels: Optional[list[str]] = None,
    base_branch: str = "main",
) -> tuple[bool, Optional[str], Optional[str]]:
    """Create a draft pull request via GitHub CLI.

    Args:
        title: PR title
        body: PR body (markdown)
        labels: List of labels to add
        base_branch: Base branch to merge into

    Returns:
        Tuple of (success, pr_url, error_message)
    """
    if not check_gh_authenticated():
        return False, None, "GitHub CLI not authenticated. Run: gh auth login"

    # Write body to temp file (to handle large bodies)
    body_file = REPO_ROOT / ".scout_pr_body.md"
    body_file.write_text(body)

    # Build command
    cmd = [
        "gh",
        "pr",
        "create",
        "--draft",
        "--title",
        title,
        "--body-file",
        str(body_file),
        "--base",
        base_branch,
    ]

    if labels:
        for label in labels:
            cmd.extend(["--label", label])

    try:
        result = run_cmd(cmd, check=False)

        # Clean up temp file
        body_file.unlink(missing_ok=True)

        if result.returncode != 0:
            return False, None, f"PR creation failed: {result.stderr}"

        # Extract PR URL from output
        pr_url = result.stdout.strip()
        return True, pr_url, None

    except Exception as e:
        body_file.unlink(missing_ok=True)
        return False, None, f"PR creation failed: {e}"


def apply_suggestion_and_pr(
    suggestion_id: int,
    dry_run: bool = False,
) -> PRResult:
    """Apply a suggestion and create a draft PR.

    Args:
        suggestion_id: ID of suggestion to apply
        dry_run: If True, show what would be done without executing

    Returns:
        PRResult with details of the operation
    """
    # Load suggestion from database
    import sqlite3
    from pathlib import Path

    AUDIT_MONITOR_DB = Path("~/.scout/audit_monitor.db").expanduser()

    if not AUDIT_MONITOR_DB.exists():
        return PRResult(
            success=False,
            branch_name=None,
            pr_url=None,
            error="Audit monitor database not found",
            changes=[],
        )

    conn = sqlite3.connect(str(AUDIT_MONITOR_DB))
    conn.row_factory = sqlite3.Row

    cursor = conn.execute(
        """
        SELECT * FROM suggestions WHERE id = ?
    """,
        (suggestion_id,),
    )

    row = cursor.fetchone()
    conn.close()

    if not row:
        return PRResult(
            success=False,
            branch_name=None,
            pr_url=None,
            error=f"Suggestion {suggestion_id} not found",
            changes=[],
        )

    if row["status"] != "new":
        return PRResult(
            success=False,
            branch_name=None,
            pr_url=None,
            error=f"Suggestion {suggestion_id} is not new (status: {row['status']})",
            changes=[],
        )

    # Extract suggestion details
    action = row["action"]
    tool_name = row["tool_name"]
    reason = row["reason"]
    suggestion = row["suggestion"]
    evidence = json.loads(row["evidence"]) if row["evidence"] else {}

    # Generate branch name
    timestamp = datetime.now().strftime("%Y%m%d%H%M")
    branch_name = f"scout-auto/{action}/{suggestion_id}-{timestamp}"

    # Create branch
    if not dry_run:
        create_branch(branch_name)

    # Apply changes based on action
    changes = []
    error = None

    if action == "adjust_config":
        # Find config key in evidence
        config_key = evidence.get("config_key", "limits.hourly_budget")
        config_value = evidence.get("config_value", 1.0)

        success, error, files = apply_config_change(config_key, config_value, dry_run)
        if not success:
            return PRResult(
                success=False, branch_name=branch_name, pr_url=None, error=error, changes=[]
            )
        changes.extend(files)

    elif action == "create_tool":
        success, error, files = create_tool_stub(tool_name, dry_run)
        if not success:
            return PRResult(
                success=False, branch_name=branch_name, pr_url=None, error=error, changes=[]
            )
        changes.extend(files)

    elif action == "add_ignore":
        file_to_ignore = evidence.get("file", "")
        success, error, files = add_to_gitignore([file_to_ignore], dry_run)
        if not success:
            return PRResult(
                success=False, branch_name=branch_name, pr_url=None, error=error, changes=[]
            )
        changes.extend(files)

    elif action == "adjust_timeout":
        # Timeout adjustments typically require config changes
        success, error, files = apply_config_change("limits.timeout_seconds", 120, dry_run)
        if not success:
            return PRResult(
                success=False, branch_name=branch_name, pr_url=None, error=error, changes=[]
            )
        changes.extend(files)

    else:
        error = f"Unknown action: {action}"
        return PRResult(
            success=False, branch_name=branch_name, pr_url=None, error=error, changes=[]
        )

    if dry_run:
        return PRResult(
            success=True,
            branch_name=branch_name,
            pr_url=None,
            error=None,
            changes=changes,
        )

    # Commit changes
    commit_msg = f"""scout: {action} based on audit analysis

## Suggestion {suggestion_id}
{reason}

## Suggestion
{suggestion}

## Evidence
{json.dumps(evidence, indent=2)}

## Changes
{chr(10).join(f"- {c}" for c in changes)}

---
Generated by Scout self-improvement system
"""

    run_cmd(["git", "add", "-A"])
    run_cmd(["git", "commit", "-m", commit_msg])
    run_cmd(["git", "push", "-u", "origin", branch_name])

    # Create draft PR
    pr_title = f"[auto] {action}: {suggestion_id} - {reason[:50]}"
    pr_body = f"""## Summary
{reason}

## Suggestion
{suggestion}

## Evidence
```json
{json.dumps(evidence, indent=2)}
```

## Changes
{chr(10).join(f"- {c}" for c in changes)}

## Notes
- This is a DRAFT PR requiring human review
- Generated by Scout self-improvement system
- Labels: self-improvement, automated
"""

    success, pr_url, pr_error = create_draft_pr(
        title=pr_title,
        body=pr_body,
        labels=["self-improvement", "automated"],
    )

    if not success:
        return PRResult(
            success=False,
            branch_name=branch_name,
            pr_url=None,
            error=pr_error,
            changes=changes,
        )

    # Update suggestion status
    conn = sqlite3.connect(str(AUDIT_MONITOR_DB))
    now = datetime.now().isoformat()
    conn.execute(
        """
        UPDATE suggestions SET status = 'applied', applied_at = ? WHERE id = ?
    """,
        (now, suggestion_id),
    )
    conn.commit()
    conn.close()

    return PRResult(
        success=True,
        branch_name=branch_name,
        pr_url=pr_url,
        error=None,
        changes=changes,
    )
