"""Scout configuration module.

This module centralizes all default configuration values (magic numbers)
into a single location for easy maintenance and modification.

Usage:
    # For default constants:
    from scout.config import (
        BUDGET_COST_PER_MILLION_8B,
        RETRY_BASE_DELAY,
        HOTSPOT_WEIGHT_CHURN,
    )

    # For ScoutConfig class:
    from scout.app_config import ScoutConfig
    config = ScoutConfig()
"""

import warnings
from typing import Any

# Re-export all defaults from config.defaults (no warning needed)
from scout.config.defaults import (
    # Budget defaults
    BUDGET_COST_PER_MILLION_8B,
    BUDGET_COST_PER_MILLION_70B,
    BUDGET_TOKENS_PER_SMALL_FILE,
    BUDGET_BRIEF_COST_PER_FILE,
    BUDGET_TASK_NAV_ESTIMATED_COST,
    BUDGET_DRAFT_COST_PER_FILE,
    BUDGET_RESERVATION_TIMEOUT_SECONDS,
    BUDGET_ALLOW_OVERAGE_PERCENT,
    BUDGET_DEFAULT_HOURLY_BUDGET,
    BUDGET_HARD_SAFETY_CAP,
    BUDGET_HOUR_SECONDS,
    BUDGET_CASCADE_BUFFER_FACTOR,

    # Retry defaults
    RETRY_BASE_DELAY,
    RETRY_MAX_DELAY,
    RETRY_MAX_RETRIES,
    RETRY_JITTER_FACTOR,

    # Circuit breaker defaults
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_SUCCESS_THRESHOLD,
    CIRCUIT_BREAKER_TIMEOUT_SECONDS,
    CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS,
    CIRCUIT_BREAKER_PROVIDER_COOLDOWN_SECONDS,

    # Rate limiter defaults
    RATELIMIT_DEFAULT_RPM,
    RATELIMIT_DEFAULT_RPD,
    RATELIMIT_RPM_WINDOW_SECONDS,
    RATELIMIT_RPD_WINDOW_SECONDS,
    RATELIMIT_DEEPSEEK_RPM,
    RATELIMIT_DEEPSEEK_TPM,
    RATELIMIT_MINIMAX_RPM,
    RATELIMIT_MINIMAX_TPM,

    # Hotspot defaults
    HOTSPOT_WEIGHT_CHURN,
    HOTSPOT_WEIGHT_ERROR,
    HOTSPOT_WEIGHT_IMPACT,
    HOTSPOT_DEFAULT_DAYS,
    HOTSPOT_MAX_CHURN,
    HOTSPOT_MAX_ERRORS,
    HOTSPOT_MAX_IMPACT,
    HOTSPOT_DEFAULT_LIMIT,

    # Trust/BM25 defaults
    BM25_BASE,
    BM25_RANGE,
    BM25_CLARITY_MAX,
    BM25_EXACT_BOOST,
    BM25_CLASS_BOOST,
    TRUST_DEFAULT_MIN_CONFIDENCE,
    TRUST_DEFAULT_LEARNER_MIN_SAMPLES,
    TRUST_DEFAULT_LEARNER_ADJUSTMENT_RATE,
    TRUST_DEFAULT_LEARNER_CONFIDENCE_THRESHOLD,
    TRUST_DEFAULT_AUTO_REPAIR_ENABLED,
    TRUST_DEFAULT_AUTO_REPAIR_THRESHOLD,

    # Audit defaults
    AUDIT_DEFAULT_LEVEL,
    AUDIT_DEFAULT_SAMPLE_RATE,
    AUDIT_LOG_FILENAME,
    TRUST_DB_FILENAME,

    # Timeout defaults
    TIMEOUT_CONNECT_DEFAULT,
    TIMEOUT_READ_DEFAULT,
    TIMEOUT_DEEPSEEK_CONNECT,
    TIMEOUT_DEEPSEEK_READ,
    TIMEOUT_MINIMAX_CONNECT,
    TIMEOUT_MINIMAX_READ,

    # Token estimation defaults
    TOKEN_ESTIMATOR_MODEL_DEFAULT,
    TOKENS_PER_CHAR_ENGLISH,
    TOKENS_PER_CHAR_CODE,
    TOKEN_ESTIMATOR_MESSAGE_OVERHEAD,
    TOKEN_ESTIMATOR_SYSTEM_MESSAGE_OVERHEAD,

    # Sliding window defaults
    SLIDING_WINDOW_REQUESTS_PER_MINUTE,
    SLIDING_WINDOW_TOKENS_PER_MINUTE,

    # Navigation defaults
    NAV_DEFAULT_CONFIDENCE,
    NAV_FALLBACK_CONFIDENCE,
    NAV_COST_8B_ESTIMATE,
    NAV_COST_70B_ESTIMATE,
    TASK_HIGH_CONFIDENCE_THRESHOLD,
    TASK_LOW_CONFIDENCE_THRESHOLD,

    # Execution & Plans defaults
    EXECUTOR_TIMEOUT_SECONDS,
    EXECUTOR_ESTIMATED_COST,
    EXECUTOR_MAX_BUDGET,
    EXECUTOR_DEFAULT_MAX_RETRIES,
    EXECUTOR_DEFAULT_TIMEOUT_SECONDS,
    BATCH_MAX_DEPTH,
    BATCH_DEFAULT_TIMEOUT,
    PLAN_LOCK_TIMEOUT_SECONDS,
    PLAN_STALE_LOCK_HOURS,
    PLAN_CRITICAL_ACTION_TYPES,
    PLAN_ARCHIVE_DAYS,
    PLAN_DELETE_DAYS,
    PLAN_CACHE_DAYS,
    STEP_DEFAULT_TIMEOUT_SECONDS,
    STEP_DEFAULT_MAX_RETRIES,
    # Safety guard defaults
    SAFETY_MAX_PATH_DEPTH,
    SAFETY_MAX_LIST_DEPTH,
    SAFETY_MAX_FILE_SIZE_KB,
    SAFETY_DEFAULT_COMMAND_TIMEOUT,
    SAFETY_MAX_WAIT_SECONDS,
    # Web step defaults
    WEBSTEP_DEFAULT_MAX_RETRIES,
    WEBSTEP_DEFAULT_TIMEOUT_SECONDS,
    # LLM parser defaults
    LLM_PARSER_DEFAULT_MAX_RETRIES,
    # VS Code parser defaults
    VSCODE_EXTENSIONS_PATH,
    VSCODE_GLOBAL_STORAGE,
    VSCODE_WORKSPACE_STORAGE,
    PARSER_MAX_RETRIES,
    PARSER_RETRY_DELAY,
    SUPPORTED_AGENTS,
    AGENT_COPILOT,
    AGENT_CLINE,
    AGENT_CONTINUE,
    COPILOT_CHAT_SESSION_INDEX,
    COPILOT_CHAT_SESSIONS_DIR,
    CLINE_EXTENSION_ID,
    CLINE_API_CONVERSATION_DIR,
    CLINE_API_CONVERSATION_FILE,
    CLINE_FALLBACK_FILE,
    CONTINUE_CONFIG_DIR,
    CONTINUE_SESSIONS_FILE,
    CONTINUE_HISTORY_DB,
)

# Deprecated items that should be imported from scout.app_config instead
_DEPRECATED_IMPORTS = {
    "ScoutConfig",
    "get_global_semaphore",
    "HARD_MAX_HOURLY_BUDGET",
    "HARD_MAX_COST_PER_EVENT",
    "HARD_MAX_AUTO_ESCALATIONS",
    "TriggerConfig",
    "DEFAULT_CONFIG",
    "EnvLoader",
}

# Cache for deprecated imports to avoid repeated imports
_deprecated_cache: dict = {}


def __getattr__(name: str) -> Any:
    """Provide deprecation warnings only for specific deprecated imports."""
    if name in _DEPRECATED_IMPORTS:
        if name not in _deprecated_cache:
            warnings.warn(
                f"Importing {name} from scout.config is deprecated. "
                f"Use scout.app_config.{name} instead.",
                DeprecationWarning,
                stacklevel=2,
            )
            # Import and cache the deprecated item
            from scout.app_config import (
                ScoutConfig,
                get_global_semaphore,
                HARD_MAX_HOURLY_BUDGET,
                HARD_MAX_COST_PER_EVENT,
                HARD_MAX_AUTO_ESCALATIONS,
                TriggerConfig,
                DEFAULT_CONFIG,
                EnvLoader,
            )

            _deprecated_cache.update({
                "ScoutConfig": ScoutConfig,
                "get_global_semaphore": get_global_semaphore,
                "HARD_MAX_HOURLY_BUDGET": HARD_MAX_HOURLY_BUDGET,
                "HARD_MAX_COST_PER_EVENT": HARD_MAX_COST_PER_EVENT,
                "HARD_MAX_AUTO_ESCALATIONS": HARD_MAX_AUTO_ESCALATIONS,
                "TriggerConfig": TriggerConfig,
                "DEFAULT_CONFIG": DEFAULT_CONFIG,
                "EnvLoader": EnvLoader,
            })
        return _deprecated_cache[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # Budget
    "BUDGET_COST_PER_MILLION_8B",
    "BUDGET_COST_PER_MILLION_70B",
    "BUDGET_TOKENS_PER_SMALL_FILE",
    "BUDGET_BRIEF_COST_PER_FILE",
    "BUDGET_TASK_NAV_ESTIMATED_COST",
    "BUDGET_DRAFT_COST_PER_FILE",
    "BUDGET_RESERVATION_TIMEOUT_SECONDS",
    "BUDGET_ALLOW_OVERAGE_PERCENT",
    "BUDGET_DEFAULT_HOURLY_BUDGET",
    "BUDGET_HARD_SAFETY_CAP",
    "BUDGET_HOUR_SECONDS",
    "BUDGET_CASCADE_BUFFER_FACTOR",
    # Retry
    "RETRY_BASE_DELAY",
    "RETRY_MAX_DELAY",
    "RETRY_MAX_RETRIES",
    "RETRY_JITTER_FACTOR",
    # Circuit breaker
    "CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "CIRCUIT_BREAKER_SUCCESS_THRESHOLD",
    "CIRCUIT_BREAKER_TIMEOUT_SECONDS",
    "CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS",
    "CIRCUIT_BREAKER_PROVIDER_COOLDOWN_SECONDS",
    # Rate limiter
    "RATELIMIT_DEFAULT_RPM",
    "RATELIMIT_DEFAULT_RPD",
    "RATELIMIT_RPM_WINDOW_SECONDS",
    "RATELIMIT_RPD_WINDOW_SECONDS",
    "RATELIMIT_DEEPSEEK_RPM",
    "RATELIMIT_DEEPSEEK_TPM",
    "RATELIMIT_MINIMAX_RPM",
    "RATELIMIT_MINIMAX_TPM",
    # Hotspots
    "HOTSPOT_WEIGHT_CHURN",
    "HOTSPOT_WEIGHT_ERROR",
    "HOTSPOT_WEIGHT_IMPACT",
    "HOTSPOT_DEFAULT_DAYS",
    "HOTSPOT_MAX_CHURN",
    "HOTSPOT_MAX_ERRORS",
    "HOTSPOT_MAX_IMPACT",
    "HOTSPOT_DEFAULT_LIMIT",
    # Trust/BM25
    "BM25_BASE",
    "BM25_RANGE",
    "BM25_CLARITY_MAX",
    "BM25_EXACT_BOOST",
    "BM25_CLASS_BOOST",
    "TRUST_DEFAULT_MIN_CONFIDENCE",
    "TRUST_DEFAULT_LEARNER_MIN_SAMPLES",
    "TRUST_DEFAULT_LEARNER_ADJUSTMENT_RATE",
    "TRUST_DEFAULT_LEARNER_CONFIDENCE_THRESHOLD",
    "TRUST_DEFAULT_AUTO_REPAIR_ENABLED",
    "TRUST_DEFAULT_AUTO_REPAIR_THRESHOLD",
    # Audit
    "AUDIT_DEFAULT_LEVEL",
    "AUDIT_DEFAULT_SAMPLE_RATE",
    "AUDIT_LOG_FILENAME",
    "TRUST_DB_FILENAME",
    # Timeout
    "TIMEOUT_CONNECT_DEFAULT",
    "TIMEOUT_READ_DEFAULT",
    "TIMEOUT_DEEPSEEK_CONNECT",
    "TIMEOUT_DEEPSEEK_READ",
    "TIMEOUT_MINIMAX_CONNECT",
    "TIMEOUT_MINIMAX_READ",
    # Token estimation
    "TOKEN_ESTIMATOR_MODEL_DEFAULT",
    "TOKENS_PER_CHAR_ENGLISH",
    "TOKENS_PER_CHAR_CODE",
    "TOKEN_ESTIMATOR_MESSAGE_OVERHEAD",
    "TOKEN_ESTIMATOR_SYSTEM_MESSAGE_OVERHEAD",
    # Sliding window
    "SLIDING_WINDOW_REQUESTS_PER_MINUTE",
    "SLIDING_WINDOW_TOKENS_PER_MINUTE",
    # Navigation
    "NAV_DEFAULT_CONFIDENCE",
    "NAV_FALLBACK_CONFIDENCE",
    "NAV_COST_8B_ESTIMATE",
    "NAV_COST_70B_ESTIMATE",
    "TASK_HIGH_CONFIDENCE_THRESHOLD",
    "TASK_LOW_CONFIDENCE_THRESHOLD",
    # Execution & Plans
    "EXECUTOR_TIMEOUT_SECONDS",
    "EXECUTOR_ESTIMATED_COST",
    "EXECUTOR_MAX_BUDGET",
    "EXECUTOR_DEFAULT_MAX_RETRIES",
    "EXECUTOR_DEFAULT_TIMEOUT_SECONDS",
    "BATCH_MAX_DEPTH",
    "BATCH_DEFAULT_TIMEOUT",
    "PLAN_LOCK_TIMEOUT_SECONDS",
    "PLAN_STALE_LOCK_HOURS",
    "PLAN_CRITICAL_ACTION_TYPES",
    "PLAN_ARCHIVE_DAYS",
    "PLAN_DELETE_DAYS",
    "PLAN_CACHE_DAYS",
    "STEP_DEFAULT_TIMEOUT_SECONDS",
    "STEP_DEFAULT_MAX_RETRIES",
    # Safety guard defaults
    "SAFETY_MAX_PATH_DEPTH",
    "SAFETY_MAX_LIST_DEPTH",
    "SAFETY_MAX_FILE_SIZE_KB",
    "SAFETY_DEFAULT_COMMAND_TIMEOUT",
    "SAFETY_MAX_WAIT_SECONDS",
    # Web step defaults
    "WEBSTEP_DEFAULT_MAX_RETRIES",
    "WEBSTEP_DEFAULT_TIMEOUT_SECONDS",
    # LLM parser defaults
    "LLM_PARSER_DEFAULT_MAX_RETRIES",
    # VS Code parser defaults
    "VSCODE_EXTENSIONS_PATH",
    "VSCODE_GLOBAL_STORAGE",
    "VSCODE_WORKSPACE_STORAGE",
    "PARSER_MAX_RETRIES",
    "PARSER_RETRY_DELAY",
    "SUPPORTED_AGENTS",
    "AGENT_COPILOT",
    "AGENT_CLINE",
    "AGENT_CONTINUE",
    "COPILOT_CHAT_SESSION_INDEX",
    "COPILOT_CHAT_SESSIONS_DIR",
    "CLINE_EXTENSION_ID",
    "CLINE_API_CONVERSATION_DIR",
    "CLINE_API_CONVERSATION_FILE",
    "CLINE_FALLBACK_FILE",
    "CONTINUE_CONFIG_DIR",
    "CONTINUE_SESSIONS_FILE",
    "CONTINUE_HISTORY_DB",
    # Deprecated (still available but with warning)
    "ScoutConfig",
    "get_global_semaphore",
    "HARD_MAX_HOURLY_BUDGET",
    "HARD_MAX_COST_PER_EVENT",
    "HARD_MAX_AUTO_ESCALATIONS",
    "TriggerConfig",
    "DEFAULT_CONFIG",
    "EnvLoader",
]
