"""Scout configuration module.

This module centralizes all default configuration values (magic numbers)
into a single location for easy maintenance and modification.
"""

from scout.config.defaults import (
    # Budget defaults
    BUDGET_COST_PER_MILLION_8B,
    BUDGET_COST_PER_MILLION_70B,
    BUDGET_TOKENS_PER_SMALL_FILE,
    BUDGET_BRIEF_COST_PER_FILE,
    BUDGET_TASK_NAV_ESTIMATED_COST,
    BUDGET_DRAFT_COST_PER_FILE,
    BUDGET_RESERVATION_TIMEOUT_SECONDS,
    BUDGET_ALLOW_OVERAGE_PERCENT,
    BUDGET_DEFAULT_HOURLY_BUDGET,
    BUDGET_HARD_SAFETY_CAP,
    BUDGET_HOUR_SECONDS,
    BUDGET_CASCADE_BUFFER_FACTOR,

    # Retry defaults
    RETRY_BASE_DELAY,
    RETRY_MAX_DELAY,
    RETRY_MAX_RETRIES,
    RETRY_JITTER_FACTOR,

    # Circuit breaker defaults
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_COOLDOWN_SECONDS,

    # Rate limiter defaults
    RATELIMIT_DEFAULT_RPM,
    RATELIMIT_DEFAULT_RPD,
    RATELIMIT_RPM_WINDOW_SECONDS,
    RATELIMIT_RPD_WINDOW_SECONDS,
    RATELIMIT_DEEPSEEK_RPM,
    RATELIMIT_DEEPSEEK_TPM,
    RATELIMIT_MINIMAX_RPM,
    RATELIMIT_MINIMAX_TPM,

    # Hotspot defaults
    HOTSPOT_WEIGHT_CHURN,
    HOTSPOT_WEIGHT_ERROR,
    HOTSPOT_WEIGHT_IMPACT,
    HOTSPOT_DEFAULT_DAYS,
    HOTSPOT_MAX_CHURN,
    HOTSPOT_MAX_ERRORS,
    HOTSPOT_MAX_IMPACT,
    HOTSPOT_DEFAULT_LIMIT,

    # Trust/BM25 defaults
    BM25_BASE,
    BM25_RANGE,
    BM25_CLARITY_MAX,
    BM25_EXACT_BOOST,
    BM25_CLASS_BOOST,
    TRUST_DEFAULT_MIN_CONFIDENCE,
    TRUST_DEFAULT_LEARNER_MIN_SAMPLES,
    TRUST_DEFAULT_LEARNER_ADJUSTMENT_RATE,
    TRUST_DEFAULT_LEARNER_CONFIDENCE_THRESHOLD,
    TRUST_DEFAULT_AUTO_REPAIR_ENABLED,
    TRUST_DEFAULT_AUTO_REPAIR_THRESHOLD,

    # Audit defaults
    AUDIT_DEFAULT_LEVEL,
    AUDIT_DEFAULT_SAMPLE_RATE,
    AUDIT_LOG_FILENAME,
    TRUST_DB_FILENAME,

    # Timeout defaults
    TIMEOUT_CONNECT_DEFAULT,
    TIMEOUT_READ_DEFAULT,
    TIMEOUT_DEEPSEEK_CONNECT,
    TIMEOUT_DEEPSEEK_READ,
    TIMEOUT_MINIMAX_CONNECT,
    TIMEOUT_MINIMAX_READ,

    # Token estimation defaults
    TOKEN_ESTIMATOR_MODEL_DEFAULT,
    TOKENS_PER_CHAR_ENGLISH,
    TOKENS_PER_CHAR_CODE,
    TOKEN_ESTIMATOR_MESSAGE_OVERHEAD,
    TOKEN_ESTIMATOR_SYSTEM_MESSAGE_OVERHEAD,

    # Sliding window defaults
    SLIDING_WINDOW_REQUESTS_PER_MINUTE,
    SLIDING_WINDOW_TOKENS_PER_MINUTE,
)

__all__ = [
    # Budget
    "BUDGET_COST_PER_MILLION_8B",
    "BUDGET_COST_PER_MILLION_70B",
    "BUDGET_TOKENS_PER_SMALL_FILE",
    "BUDGET_BRIEF_COST_PER_FILE",
    "BUDGET_TASK_NAV_ESTIMATED_COST",
    "BUDGET_DRAFT_COST_PER_FILE",
    "BUDGET_RESERVATION_TIMEOUT_SECONDS",
    "BUDGET_ALLOW_OVERAGE_PERCENT",
    "BUDGET_DEFAULT_HOURLY_BUDGET",
    "BUDGET_HARD_SAFETY_CAP",
    "BUDGET_HOUR_SECONDS",
    "BUDGET_CASCADE_BUFFER_FACTOR",
    # Retry
    "RETRY_BASE_DELAY",
    "RETRY_MAX_DELAY",
    "RETRY_MAX_RETRIES",
    "RETRY_JITTER_FACTOR",
    # Circuit breaker
    "CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "CIRCUIT_BREAKER_COOLDOWN_SECONDS",
    # Rate limiter
    "RATELIMIT_DEFAULT_RPM",
    "RATELIMIT_DEFAULT_RPD",
    "RATELIMIT_RPM_WINDOW_SECONDS",
    "RATELIMIT_RPD_WINDOW_SECONDS",
    "RATELIMIT_DEEPSEEK_RPM",
    "RATELIMIT_DEEPSEEK_TPM",
    "RATELIMIT_MINIMAX_RPM",
    "RATELIMIT_MINIMAX_TPM",
    # Hotspots
    "HOTSPOT_WEIGHT_CHURN",
    "HOTSPOT_WEIGHT_ERROR",
    "HOTSPOT_WEIGHT_IMPACT",
    "HOTSPOT_DEFAULT_DAYS",
    "HOTSPOT_MAX_CHURN",
    "HOTSPOT_MAX_ERRORS",
    "HOTSPOT_MAX_IMPACT",
    "HOTSPOT_DEFAULT_LIMIT",
    # Trust/BM25
    "BM25_BASE",
    "BM25_RANGE",
    "BM25_CLARITY_MAX",
    "BM25_EXACT_BOOST",
    "BM25_CLASS_BOOST",
    "TRUST_DEFAULT_MIN_CONFIDENCE",
    "TRUST_DEFAULT_LEARNER_MIN_SAMPLES",
    "TRUST_DEFAULT_LEARNER_ADJUSTMENT_RATE",
    "TRUST_DEFAULT_LEARNER_CONFIDENCE_THRESHOLD",
    "TRUST_DEFAULT_AUTO_REPAIR_ENABLED",
    "TRUST_DEFAULT_AUTO_REPAIR_THRESHOLD",
    # Audit
    "AUDIT_DEFAULT_LEVEL",
    "AUDIT_DEFAULT_SAMPLE_RATE",
    "AUDIT_LOG_FILENAME",
    "TRUST_DB_FILENAME",
    # Timeout
    "TIMEOUT_CONNECT_DEFAULT",
    "TIMEOUT_READ_DEFAULT",
    "TIMEOUT_DEEPSEEK_CONNECT",
    "TIMEOUT_DEEPSEEK_READ",
    "TIMEOUT_MINIMAX_CONNECT",
    "TIMEOUT_MINIMAX_READ",
    # Token estimation
    "TOKEN_ESTIMATOR_MODEL_DEFAULT",
    "TOKENS_PER_CHAR_ENGLISH",
    "TOKENS_PER_CHAR_CODE",
    "TOKEN_ESTIMATOR_MESSAGE_OVERHEAD",
    "TOKEN_ESTIMATOR_SYSTEM_MESSAGE_OVERHEAD",
    # Sliding window
    "SLIDING_WINDOW_REQUESTS_PER_MINUTE",
    "SLIDING_WINDOW_TOKENS_PER_MINUTE",
]
